config/routes.rb
Rails.application.routes.draw do
  resources :validate_percentages

  devise_for :users

  resources :kuizuws
  resources :users
  resources :checkcercentage

  get '/quiz', to: 'quiz#index'
  post '/validate', to:'quiz#validate'  
  get '/summary', to: 'quiz#summary'
 
  root :to => 'home#index'
  get '404', to: redirect('/')
 

end

app/models/kuizuw.rb
class Kuizuw < ActiveRecord::Base
end

app/controllers/kuizuws_controller.rb
class KuizuwsController < ApplicationController
  before_action :set_kuizuw, only: [:show, :edit, :update, :destroy]

  # GET /kuizuws
  # GET /kuizuws.json
  def index
    @kuizuws = Kuizuw.all
  end

  # GET /kuizuws/1
  # GET /kuizuws/1.json
  def show
  end

  # GET /kuizuws/new
  def new
    @kuizuw = Kuizuw.new
  end

  # GET /kuizuws/1/edit
  def edit
  end

  # POST /kuizuws
  # POST /kuizuws.json
  def create
    @kuizuw = Kuizuw.new(kuizuw_params)

    respond_to do |format|
      if @kuizuw.save
        format.html { redirect_to @kuizuw, notice: 'Kuizuw was successfully created.' }
        format.json { render :show, status: :created, location: @kuizuw }
      else
        format.html { render :new }
        format.json { render json: @kuizuw.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kuizuws/1
  # PATCH/PUT /kuizuws/1.json
  def update
    respond_to do |format|
      if @kuizuw.update(kuizuw_params)
        format.html { redirect_to @kuizuw, notice: 'Kuizuw was successfully updated.' }
        format.json { render :show, status: :ok, location: @kuizuw }
      else
        format.html { render :edit }
        format.json { render json: @kuizuw.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kuizuws/1
  # DELETE /kuizuws/1.json
  def destroy
    @kuizuw.destroy
    respond_to do |format|
      format.html { redirect_to kuizuws_url, notice: 'Kuizuw was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kuizuw
      @kuizuw = Kuizuw.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kuizuw_params
      params.require(:kuizuw).permit(:anumber)
    end
end

app/helpers/kuizuws_helper.rb
module KuizuwsHelper
end

app/views/kuizuws/_form.html.erb
<%= form_for(@kuizuw) do |f| %>
  <% if @kuizuw.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kuizuw.errors.count, "error") %> prohibited this kuizuw from being saved:</h2>

      <ul>
      <% @kuizuw.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :anumber %><br>
    <%= f.number_field :anumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kuizuws/edit.html.erb
<h1>Editing Kuizuw</h1>

<%= render 'form' %>

<%= link_to 'Show', @kuizuw %> |
<%= link_to 'Back', kuizuws_path %>

app/views/kuizuws/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Kuizuws</h1>

<table>
  <thead>
    <tr>
      <th>Anumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kuizuws.each do |kuizuw| %>
      <tr>
        <td><%= kuizuw.anumber %></td>
        <td><%= link_to 'Show', kuizuw %></td>
        <td><%= link_to 'Edit', edit_kuizuw_path(kuizuw) %></td>
        <td><%= link_to 'Destroy', kuizuw, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kuizuw', new_kuizuw_path %>

app/views/kuizuws/new.html.erb
<h1>New Kuizuw</h1>

<%= render 'form' %>

<%= link_to 'Back', kuizuws_path %>

app/views/kuizuws/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Anumber:</strong>
  <%= @kuizuw.anumber %>
</p>

<%= link_to 'Edit', edit_kuizuw_path(@kuizuw) %> |
<%= link_to 'Back', kuizuws_path %>