config/routes.rb
Rails.application.routes.draw do
  resources :validate_percentages

  devise_for :users

  resources :kuizuws
  resources :users
  resources :checkcercentage

  get '/quiz', to: 'quiz#index'
  post '/validate', to:'quiz#validate'  
  get '/summary', to: 'quiz#summary'
 
  root :to => 'home#index'
  get '404', to: redirect('/')
 

end

app/models/validate_percentage.rb
class ValidatePercentage < ActiveRecord::Base

	#1) what is  x% of y?
	def findAmount(rate, base)
		resultAmount = rate * base/100
		return resultAmount
	end 

	#2) x is what percentage of y?
	def findPercent(amount, base  )
		resultPercent = amount/base * 100
		return resultPercent
	end

	  #3) x is y% of what number?
	def findBase(amount, rate)
		resultBase = amount/rate *100
		return resultBase
	end
end

app/controllers/validate_percentages_controller.rb
class ValidatePercentagesController < ApplicationController
  before_action :set_validate_percentage, only: [:show, :edit, :update, :destroy]

  # GET /validate_percentages
  # GET /validate_percentages.json
  def index
   
    @randomNumber1 = 0;
    @randomNumber2 = 55;

  end

  def validateanswer
      format.html { redirect_to @validate_percentage, notice: 'Validate percentage was successfully created.' }
      format.json { render :show, status: :created, location: @validate_percentage }
  end
  
  # GET /validate_percentages/new
  def new
    @validate_percentage = ValidatePercentage.new
  end

  # GET /validate_percentages/1/edit
  def edit
  end

  # POST /validate_percentages
  # POST /validate_percentages.json
  def create
    @validate_percentage = ValidatePercentage.new(validate_percentage_params)

    respond_to do |format|
      if @validate_percentage.save
        format.html { redirect_to @validate_percentage, notice: 'Validate percentage was successfully created.' }
        format.json { render :show, status: :created, location: @validate_percentage }
      else
        format.html { render :new }
        format.json { render json: @validate_percentage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validate_percentages/1
  # PATCH/PUT /validate_percentages/1.json
  def update
    respond_to do |format|
      if @validate_percentage.update(validate_percentage_params)
        format.html { redirect_to @validate_percentage, notice: 'Validate percentage was successfully updated.' }
        format.json { render :show, status: :ok, location: @validate_percentage }
      else
        format.html { render :edit }
        format.json { render json: @validate_percentage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validate_percentages/1
  # DELETE /validate_percentages/1.json
  def destroy
    @validate_percentage.destroy
    respond_to do |format|
      format.html { redirect_to validate_percentages_url, notice: 'Validate percentage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validate_percentage
      @validate_percentage = ValidatePercentage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def validate_percentage_params
      params[:validate_percentage]
    end
end

app/helpers/validate_percentages_helper.rb
module ValidatePercentagesHelper
end

app/views/validate_percentages/_form.html.erb
<%= form_for(@validate_percentage) do |f| %>
  <% if @validate_percentage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validate_percentage.errors.count, "error") %> prohibited this validate_percentage from being saved:</h2>

      <ul>
      <% @validate_percentage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/validate_percentages/edit.html.erb
<h1>Editing Validate Percentage</h1>

<%= render 'form' %>

<%= link_to 'Show', @validate_percentage %> |
<%= link_to 'Back', validate_percentages_path %>

app/views/validate_percentages/index.html.erb
<p id="notice"><%= notice %></p>

<br>

<h1>What is the percentage of <%= @randomNumber1 %> percentage of <%= @randomNumber2 %>?</h1>
<%= form_tag("/validateanswer", method: "post") do %>
 <%= label_tag(:userAnswer, "Answer:") %>
 <%= text_field_tag(:userAnswer) %>
 <%= submit_tag("Submit Asnwer") %>
<% end %>

app/views/validate_percentages/new.html.erb
<h1>New Validate Percentage</h1>

<%= render 'form' %>

<%= link_to 'Back', validate_percentages_path %>

app/views/validate_percentages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_validate_percentage_path(@validate_percentage) %> |
<%= link_to 'Back', validate_percentages_path %>